// <auto-generated />
using System;
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Views.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20251202063627_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LMS.Entities.BanSaoSach", b =>
                {
                    b.Property<string>("IdBanSaoSach")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdSach")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrangSach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdBanSaoSach");

                    b.HasIndex("IdSach");

                    b.ToTable("BanSaoSach");
                });

            modelBuilder.Entity("LMS.Entities.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("IdChiTietPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChiTietPhieuMuon"));

                    b.Property<string>("IdBanSaoSach")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdPhieuMuon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TinhTrangTra")
                        .HasColumnType("longtext");

                    b.HasKey("IdChiTietPhieuMuon");

                    b.HasIndex("IdBanSaoSach");

                    b.HasIndex("IdPhieuMuon");

                    b.ToTable("ChiTietPhieuMuon");
                });

            modelBuilder.Entity("LMS.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("IdChiTietPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChiTietPhieuNhap"));

                    b.Property<decimal>("GiaTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("IdPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("IdSach")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdChiTietPhieuNhap");

                    b.HasIndex("IdPhieuNhap");

                    b.HasIndex("IdSach");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("LMS.Entities.ChiTietPhieuPhat", b =>
                {
                    b.Property<int>("IdChiTietPhieuPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChiTietPhieuPhat"));

                    b.Property<int>("IdChiTietPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("IdMucPhat")
                        .HasColumnType("int");

                    b.Property<int>("IdPhieuPhat")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayTreHen")
                        .HasColumnType("int");

                    b.Property<decimal>("TienPhatTra")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdChiTietPhieuPhat");

                    b.HasIndex("IdChiTietPhieuMuon");

                    b.HasIndex("IdMucPhat");

                    b.HasIndex("IdPhieuPhat");

                    b.ToTable("ChiTietPhieuPhat");
                });

            modelBuilder.Entity("LMS.Entities.DocGia", b =>
                {
                    b.Property<int>("IdDocGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDocGia"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SDT")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDocGia")
                        .HasColumnType("longtext");

                    b.HasKey("IdDocGia");

                    b.ToTable("DocGia");
                });

            modelBuilder.Entity("LMS.Entities.MucPhat", b =>
                {
                    b.Property<int>("IdMucPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMucPhat"));

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SoTienPhat")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TenMucPhat")
                        .HasColumnType("longtext");

                    b.HasKey("IdMucPhat");

                    b.ToTable("MucPhat");
                });

            modelBuilder.Entity("LMS.Entities.NCC", b =>
                {
                    b.Property<int>("IdNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNCC"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("SDT")
                        .HasColumnType("longtext");

                    b.Property<string>("TenNCC")
                        .HasColumnType("longtext");

                    b.HasKey("IdNCC");

                    b.ToTable("NCC");
                });

            modelBuilder.Entity("LMS.Entities.NXB", b =>
                {
                    b.Property<int>("IdNXB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNXB"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("SDT")
                        .HasColumnType("longtext");

                    b.Property<string>("TenNXB")
                        .HasColumnType("longtext");

                    b.HasKey("IdNXB");

                    b.ToTable("NXB");
                });

            modelBuilder.Entity("LMS.Entities.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SDT")
                        .HasColumnType("longtext");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("longtext");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("LMS.Entities.PhieuMuon", b =>
                {
                    b.Property<int>("IdPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPhieuMuon"));

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("IdTheThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHenTra")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPhieuMuon");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdTheThanhVien");

                    b.ToTable("PhieuMuon");
                });

            modelBuilder.Entity("LMS.Entities.PhieuNhap", b =>
                {
                    b.Property<int>("IdPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPhieuNhap"));

                    b.Property<int>("IdNCC")
                        .HasColumnType("int");

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhieuNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SoLuongSach")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTienNhap")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdPhieuNhap");

                    b.HasIndex("IdNCC");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("LMS.Entities.PhieuPhat", b =>
                {
                    b.Property<int>("IdPhieuPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPhieuPhat"));

                    b.Property<string>("LyDoPhat")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TienPhatPhaiNop")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPhieuPhat");

                    b.ToTable("PhieuPhat");
                });

            modelBuilder.Entity("LMS.Entities.Quyen", b =>
                {
                    b.Property<int>("IdQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdQuyen"));

                    b.Property<string>("MaQuyen")
                        .HasColumnType("longtext");

                    b.Property<string>("TenQuyen")
                        .HasColumnType("longtext");

                    b.HasKey("IdQuyen");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("LMS.Entities.Sach", b =>
                {
                    b.Property<int>("IdSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSach"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdNXB")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBanSao")
                        .HasColumnType("int");

                    b.Property<int>("SoTrang")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .HasColumnType("longtext");

                    b.HasKey("IdSach");

                    b.HasIndex("IdNXB");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("LMS.Entities.TacGia", b =>
                {
                    b.Property<int>("IdTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTacGia"));

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("longtext");

                    b.Property<string>("SDT")
                        .HasColumnType("longtext");

                    b.Property<string>("TenTacGia")
                        .HasColumnType("longtext");

                    b.HasKey("IdTacGia");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("LMS.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("longtext");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("longtext");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdVaiTro");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("LMS.Entities.TheLoai", b =>
                {
                    b.Property<int>("IdTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTheLoai"));

                    b.Property<string>("TenTheloai")
                        .HasColumnType("longtext");

                    b.HasKey("IdTheLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("LMS.Entities.TheThanhVien", b =>
                {
                    b.Property<int>("IdTheThanhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTheThanhVien"));

                    b.Property<int>("IdDocGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTheThanhVien");

                    b.HasIndex("IdDocGia");

                    b.ToTable("TheThanhVien");
                });

            modelBuilder.Entity("LMS.Entities.VaiTro", b =>
                {
                    b.Property<int>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("longtext");

                    b.HasKey("IdVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("Sach_TacGia", b =>
                {
                    b.Property<int>("IdSach")
                        .HasColumnType("int");

                    b.Property<int>("IdTacGia")
                        .HasColumnType("int");

                    b.HasKey("IdSach", "IdTacGia");

                    b.HasIndex("IdTacGia");

                    b.ToTable("Sach_TacGia", (string)null);
                });

            modelBuilder.Entity("Sach_TheLoai", b =>
                {
                    b.Property<int>("IdSach")
                        .HasColumnType("int");

                    b.Property<int>("IdTheLoai")
                        .HasColumnType("int");

                    b.HasKey("IdSach", "IdTheLoai");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("Sach_TheLoai", (string)null);
                });

            modelBuilder.Entity("VaiTro_Quyen", b =>
                {
                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("IdQuyen")
                        .HasColumnType("int");

                    b.HasKey("IdVaiTro", "IdQuyen");

                    b.HasIndex("IdQuyen");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("LMS.Entities.BanSaoSach", b =>
                {
                    b.HasOne("LMS.Entities.Sach", "Sach")
                        .WithMany("BanSaoSachs")
                        .HasForeignKey("IdSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LMS.Entities.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("LMS.Entities.BanSaoSach", "BanSaoSach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("IdBanSaoSach");

                    b.HasOne("LMS.Entities.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("IdPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanSaoSach");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LMS.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("LMS.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("IdPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("IdSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LMS.Entities.ChiTietPhieuPhat", b =>
                {
                    b.HasOne("LMS.Entities.ChiTietPhieuMuon", "ChiTietPhieuMuon")
                        .WithMany()
                        .HasForeignKey("IdChiTietPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.MucPhat", "MucPhat")
                        .WithMany("ChiTietPhieuPhats")
                        .HasForeignKey("IdMucPhat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.PhieuPhat", "PhieuPhat")
                        .WithMany("ChiTietPhieuPhats")
                        .HasForeignKey("IdPhieuPhat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietPhieuMuon");

                    b.Navigation("MucPhat");

                    b.Navigation("PhieuPhat");
                });

            modelBuilder.Entity("LMS.Entities.NhanVien", b =>
                {
                    b.HasOne("LMS.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LMS.Entities.PhieuMuon", b =>
                {
                    b.HasOne("LMS.Entities.NhanVien", "NhanVien")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.TheThanhVien", "TheThanhVien")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("IdTheThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TheThanhVien");
                });

            modelBuilder.Entity("LMS.Entities.PhieuNhap", b =>
                {
                    b.HasOne("LMS.Entities.NCC", "NCC")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("IdNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NCC");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LMS.Entities.Sach", b =>
                {
                    b.HasOne("LMS.Entities.NXB", "NXB")
                        .WithMany("Sachs")
                        .HasForeignKey("IdNXB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NXB");
                });

            modelBuilder.Entity("LMS.Entities.TaiKhoan", b =>
                {
                    b.HasOne("LMS.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("LMS.Entities.TheThanhVien", b =>
                {
                    b.HasOne("LMS.Entities.DocGia", "DocGia")
                        .WithMany("TheThanhViens")
                        .HasForeignKey("IdDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("Sach_TacGia", b =>
                {
                    b.HasOne("LMS.Entities.Sach", null)
                        .WithMany()
                        .HasForeignKey("IdSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.TacGia", null)
                        .WithMany()
                        .HasForeignKey("IdTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sach_TheLoai", b =>
                {
                    b.HasOne("LMS.Entities.Sach", null)
                        .WithMany()
                        .HasForeignKey("IdSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VaiTro_Quyen", b =>
                {
                    b.HasOne("LMS.Entities.Quyen", null)
                        .WithMany()
                        .HasForeignKey("IdQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Entities.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("IdVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Entities.BanSaoSach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LMS.Entities.DocGia", b =>
                {
                    b.Navigation("TheThanhViens");
                });

            modelBuilder.Entity("LMS.Entities.MucPhat", b =>
                {
                    b.Navigation("ChiTietPhieuPhats");
                });

            modelBuilder.Entity("LMS.Entities.NCC", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("LMS.Entities.NXB", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("LMS.Entities.NhanVien", b =>
                {
                    b.Navigation("PhieuMuons");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("LMS.Entities.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LMS.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("LMS.Entities.PhieuPhat", b =>
                {
                    b.Navigation("ChiTietPhieuPhats");
                });

            modelBuilder.Entity("LMS.Entities.Sach", b =>
                {
                    b.Navigation("BanSaoSachs");
                });

            modelBuilder.Entity("LMS.Entities.TaiKhoan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("LMS.Entities.TheThanhVien", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LMS.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
